FROM node:9-alpine

WORKDIR /home/node/app

# Install deps
COPY ./package* ./
RUN npm install && \
    npm cache clean --force && \
    npm run db:migrate

COPY . .

EXPOSE 8080

# Start the app
CMD npm run test