version: '3.3'

services:
  app:
    build:
      dockerfile: Dockerfile-test
      context: .
    command: npm run test
    ports:
       - "8080:8080"
    volumes:
      - "./src:/home/node/app/src"
    env_file:
     - ./.env
    depends_on:
      - db

  db:
    build: ./schema
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
        - "3306:3306"
    volumes:
        - "./schema:/docker-entrypoint-initdb.d/:ro"
    env_file:
      - ./.env